spring:
  datasource:
    initialization-mode: always

logging:
  level:
    blog.gerberding.sandra.rating: debug

---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: rating
    password: djfgsurt459jdsif
---
spring:
  profiles: staging

---
spring:
  profiles: production